<?xml version="1.0"?>

<robot name="limo_steering_hinge" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find limo_description)/urdf/inertial_macros.xacro" />
    <xacro:macro name="limo_left_steering_hinge" params="parent_prefix wheel_prefix *joint_pose">
        <link name="${wheel_prefix}">
            <inertial>
              <mass value="0.25" />
              <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
              <origin xyz="0 0 0" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                  <cylinder length="0.0001" radius="0.0001" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius-0.01}" />
                </geometry>
            </collision>
        </link>



        <joint name="${wheel_prefix}_steering" type="revolute">
            <parent link="${parent_prefix}"/>
            <child link="${wheel_prefix}"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 0 1" />
            <limit lower="-0.698132" upper="0.698132" effort="1000" velocity="1.0" />
            <dynamics damping="1.0" friction="2.0"/>

        </joint>

        <link name="${wheel_prefix}_wheel_link">
          <!-- <inertial>
            <mass value="0.25" />
            <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
            <origin xyz="0 0 0" />

          </inertial> -->
          <visual>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
                  <mesh filename="file://$(find limo_description)/meshes/limo_optimal_wheels.dae" />
              </geometry>
          </visual>
            <collision>
                <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}"  h="${wheel_length}" />
      </link>

        <joint name="${wheel_prefix}_wheel" type="continuous">
          <parent link="${wheel_prefix}"/>
          <child link="${wheel_prefix}_wheel_link"/>
          <origin xyz="0 0 0" rpy="0 0  0" />
          <axis xyz="0 1 0"/>
          <limit effort="100.0" velocity="10.0"/>
      </joint>
    </xacro:macro>


     <xacro:macro name="limo_right_steering_hinge" params="parent_prefix wheel_prefix *joint_pose">
        <link name="${wheel_prefix}">
          <inertial>
            <mass value="0.25" />
            <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
            <origin xyz="0 0 0" />

          </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                  <cylinder length="0.0001" radius="0.0001" />
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius-0.01}" />
                </geometry>
            </collision>
        </link>

        <joint name="${wheel_prefix}_steering" type="revolute">
            <parent link="${parent_prefix}"/>
            <child link="${wheel_prefix}"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 0 -1"/>
            <limit lower="-0.698132" upper="0.698132" effort="1000" velocity="1.0" />
            <dynamics damping="1.0" friction="2.0"/>
        </joint>
        
        <link name="front_right_wheel_link">
          <!-- <inertial>
            <mass value="0.25" />
            <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
            <origin xyz="0 0 0" />
          </inertial> -->
          <visual>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
                  <mesh filename="file://$(find limo_description)/meshes/limo_optimal_wheels.dae" />
              </geometry>
          </visual>
          <collision>
            <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
          </collision>
          <xacro:cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}"  h="${wheel_length}" />
      </link>


      <joint name="${wheel_prefix}_wheel" type="continuous">
          <parent link="${wheel_prefix}"/>
          <child link="front_right_wheel_link"/>
          <origin xyz="0 0 0" rpy="0 0  0" />
          <axis xyz="0 -1 0"/>
          <limit effort="100.0" velocity="10.0"/>
      </joint>
    </xacro:macro>
</robot>