<?xml version="1.0"?>
<robot name="limo_xacro" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="limo_wheel" params="parent_prefix wheel_prefix reflect *joint_pose visual_on:=true fixed_on:=false">
        <link name="${wheel_prefix}_wheel_link">
            <!-- <inertial>
                <origin xyz="0 0 0" />
                <mass value="0.5" />
                <inertia ixx="0.01055" ixy="0" ixz="0" iyy="0.00075" iyz="0" izz="0.01055" />
            </inertial> -->
            <xacro:if value="${visual_on}">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0" />
                    <geometry>
                        <mesh filename="file://$(find limo_description)/meshes/limo_optimal_wheels.dae" />
                    </geometry>
                </visual>
            </xacro:if>
            <collision>
              <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
              <geometry>
                  <cylinder length="${wheel_length}" radius="${wheel_radius}" />
              </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}"  h="${wheel_length}" />
        </link>

        <xacro:if value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="fixed">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
            </joint>
        </xacro:if>
        <xacro:unless value="${fixed_on}">
            <joint name="${wheel_prefix}_wheel" type="continuous">
                <parent link="${parent_prefix}"/>
                <child link="${wheel_prefix}_wheel_link"/>
                <xacro:insert_block name="joint_pose"/>
                <axis xyz="0 ${reflect*1} 0"/>
                <limit effort="100.0" velocity="10.0"/>
            </joint>
        </xacro:unless>


           
    </xacro:macro>


    <!-- <xacro:macro name="limo_wheel" params="parent_prefix wheel_prefix reflect *joint_pose">
        <link name="${wheel_prefix}_wheel_link">
            <inertial>
                <origin xyz="0 0 0" />
                <mass value="0.5" />
                <inertia ixx="0.01055" ixy="0" ixz="0" iyy="0.00075" iyz="0" izz="0.01055" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find limo_description)/meshes/limo_wheel.dae" />
                </geometry>
            </visual>
            <collision>
              <origin xyz="0 ${wheel_length/2} 0" rpy="1.57 0 0" />
              <geometry>
                  <cylinder length="${wheel_length}" radius="${wheel_radius}" />
              </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix  m="${wheel_mass}" r="${wheel_radius}"  h="${wheel_length}" />
        </link>

        <joint name="${wheel_prefix}_wheel" type="continuous">
            <parent link="${parent_prefix}"/>
            <child link="${wheel_prefix}_wheel_link"/>
            <xacro:insert_block name="joint_pose"/>
            <axis xyz="0 ${reflect*1} 0"/>
        </joint>
    </xacro:macro> -->


    <xacro:macro name="limo_laser" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <visual name='laser_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.02" length="0.01"/>
                </geometry>
                <material name='laser_material'>
                    <color rgba="0.75 0.75 0.75 1" />
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
            <collision name='laser_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.032" length="0.016"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="laser_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
            <sensor name="laser" type="ray">
            <always_on>true</always_on>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>120</samples>
                    <resolution>1.000000</resolution>
                    <min_angle>-3.14159</min_angle>
                    <max_angle>3.14159</max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.3</min>
                <max>15.0</max>
                <resolution>0.015</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                <remapping>~/out:=scan</remapping>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_link</frame_name>
            </plugin>
            </sensor>
        </gazebo>
    </xacro:macro> 

    <xacro:macro name="limo_depth_camera" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <!-- <visual name='depth_camera_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </visual> -->
            <collision name='depth_camera_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.06 0.015"/>
                </geometry>
            </collision>

        </link>
    
        <joint type="fixed" name="depth_camera_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <link name="depth_link"></link>

        <joint name="${frame_prefix}_to_camera_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2} "/>
            <parent link="${frame_prefix}_link"/>
            <child link="depth_link"/>
        </joint>

            <link name="camera_depth_optical_frame"/>

        <joint name="camera_depth_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
            <parent link="depth_camera_link" />
            <child link="camera_depth_optical_frame" />
        </joint>


        <gazebo reference="${frame_prefix}_link">
            <material>Gazebo/Yellow</material>
            <sensor name="sensor_camera" type="depth">
                <pose>0.0 0.0 0.0 0.0 0.0 0.0</pose>
                <always_on>1</always_on>
                <update_rate>10</update_rate>
                <visualize>1</visualize>

                <camera name="limo_camera">
                <image>
                    <format>R8G8B8</format>
                    <width>400</width>
                    <height>400</height>
                </image>
                <clip>
                    <near>0.01</near>
                    <far>10.0</far>
                </clip>
                </camera>

                <plugin name="gazebo_ros_depth_camera_sensor" filename="libgazebo_ros_camera.so">
                    <ros>
                        <namespace>/limo</namespace>
                        <ros-args>
                            <remap from="limo_camera/image_raw" to="limo_camera/image"/>
                            <remap from="limo_camera/image_depth" to="limo_camera/depth/camera_image_depth"/>
                            <remap from="limo_camera/camera_info" to="limo_camera/camera_info_raw"/>
                            <remap from="limo_camera/camera_info_depth" to="limo_camera/camera_info_depth"/>
                            <remap from="limo_camera/points" to="limo_camera/camera_points"/>
                        </ros-args>
                    </ros>
                    <camera_name>depth_camera_link</camera_name>
                    <frame_name>camera_depth_optical_frame</frame_name>
                    <hack_baseline>0.07</hack_baseline>
                    <min_depth>0.001</min_depth>
                </plugin>

            </sensor>
        </gazebo>
    </xacro:macro>

    <xacro:macro name="limo_imu" params="parent_prefix frame_prefix  *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.01"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-7" ixy="0" ixz="0"
                    iyy="1e-7" iyz="0"
                    izz="1e-7"
                />
            </inertial>
            <visual name='imu_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
                <material name='imu_material'>
                    <color rgba="0.75 0.75 0.75 1" />
                    <ambient>0.1 0.1 0.1 1</ambient>
                    <diffuse>0.1 0.1 0.2 1</diffuse>
                    <specular>0 0 0 0</specular>
                    <emissive>0 0 0 1</emissive>
                </material>
            </visual>
            <collision name='imu_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="imu_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <gazebo reference="imu_link">
            <gravity>true</gravity>
            <sensor name="twr_imu" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <visualize>true</visualize>
            <imu>
                <orientation>
                <x>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-3</stddev>
                    </noise>
                </x>
                <y>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-3</stddev>
                    </noise>
                </y>
                <z>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-3</stddev>
                    </noise>
                </z>
                </orientation>
                <angular_velocity>
                <x>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-4</stddev>
                    </noise>
                </x>
                <y>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-4</stddev>
                    </noise>
                </y>
                <z>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-4</stddev>
                    </noise>
                </z>
                </angular_velocity>
                <linear_acceleration>
                <x>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>1.7e-2</stddev>
                    </noise>
                </x>
                <y>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>1.7e-2</stddev>
                    </noise>
                </y>
                <z>
                    <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>1.7e-2</stddev>
                    </noise>
                </z>
                </linear_acceleration>
            </imu>
            <plugin name="two_wheeled_robot_imu" filename="libgazebo_ros_imu_sensor.so">
                <initial_orientation_as_reference>false</initial_orientation_as_reference>
                <frame_name>imu_link</frame_name>
                <ros>
                <remapping>~/out:=imu</remapping>
                </ros>
            </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>


    <!-- <xacro:macro name="limo_gps" params="parent_prefix frame_prefix *joint_pose">
        <link name='${frame_prefix}_link'>
            <pose>0 0 0 0 0 0</pose>
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0.0 0 0" rpy="0 0 0"/>
                <inertia
                    ixx="1e-6" ixy="0" ixz="0"
                    iyy="1e-6" iyz="0"
                    izz="1e-6"
                />
            </inertial>
            <visual name='gps_visual'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
                <material name='gps_material'>
                    <color rgba="0.75 0.75 0.75 1" />
                </material>
            </visual>
            <collision name='gps_collision'>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.02 0.02 0.02"/>
                </geometry>
            </collision>
        </link>
        <joint type="fixed" name="gps_joint">
            <xacro:insert_block name="joint_pose"/>
            <child link="${frame_prefix}_link"/>
            <parent link="${parent_prefix}"/>
        </joint>
        <gazebo reference="${frame_prefix}_link">
            <sensor name="gps_sensor" type="gps">
                <always_on>true</always_on>
                <update_rate>10</update_rate>
                <plugin name="gps_plugin" filename="libgazebo_ros_gps.so">
                    <ros>
                        <namespace>/gps</namespace>
                        <remapping>~/out:=data</remapping>
                    </ros>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro> -->

</robot>