controller_manager:
  ros__parameters:
    update_rate: 2000  # Hz

    # Broadcaster for publishing joint states
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Velocity controller for rear wheels (Ackermann drive)
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    # Position controller for steering joints
    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

velocity_controllers:
  ros__parameters:
    use_sim_time: true
    joints: 
      - rear_left_wheel
      - rear_right_wheel
      # - front_left_wheel
      # - front_right_wheel
    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - effort

joint_state_publisher:
  ros__parameters:
    source_list:
      - /joint_trajectory_position_controller/state
    joints:
    - front_left_steering
    - front_right_steering
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
      - effort



joint_trajectory_position_controller:
  ros__parameters:
    joints:
    - front_left_steering
    - front_right_steering
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity


# robot_state_publisher:
#   ros__parameters:
#     use_sim_time: true
#     publish_frequency: 100  # Hz


#     state_publish_rate: 50 # Defaults to 50
#     action_monitor_rate: 20 # Defaults to 20

#     allow_partial_joints_goal: false # Defaults to false
#     open_loop_control: true
#     allow_integration_in_goal_trajectories: true
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)

# odom:
#   ros__parameters:
#     use_sim_time: true
#     odometry_frame: "base_link"  # 🔹 Set odom frame to base_link
#     base_frame: "base_link"

#     publish_odom: true
#     publish_odom_tf: false  # 🔹 Prevents publishing odom → base_link transform

#     max_speed: 2.0
#     max_steer: 0.5236
